[package]
name = "RustyBird"
version = "0.1.0"
edition = "2023"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.10.1"
bevy_prototype_debug_lines = "0.10"
rand = "0.8.4"
